<?php

return [
    'adminEmail' => 'kevin@kevinfirmin.com',

    'restaurantFileUploadUrl' => 'uploads/restaurant/',
    'mealFileUploadUrl' => 'uploads/meal/',

    'us_states' => [
        'AL' => 'Alabama',
        'AK' => 'Alaska',
        'AZ' => 'Arizona',
        'AR' => 'Arkansas',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DE' => 'Delaware',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'IA' => 'Iowa',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'ME' => 'Maine',
        'MD' => 'Maryland',
        'MA' => 'Massachusetts',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MS' => 'Mississippi',
        'MO' => 'Missouri',
        'MT' => 'Montana',
        'NE' => 'Nebraska',
        'NV' => 'Nevada',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NY' => 'New York',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VT' => 'Vermont',
        'VA' => 'Virginia',
        'WA' => 'Washington',
        'WV' => 'West Virginia',
        'WI' => 'Wisconsin',
        'WY' => 'Wyoming',
        'DC' => 'Washington D.C.'
    ],

    'yesNoArray' => [
        'Y' => 'Yes',
        'N' => 'No',
    ],

    'daysOfWeek' => [
        'Mon' => 'Monday',
        'Tues' => 'Tuesday',
        'Wed' => 'Wednesday',
        'Thur' => 'Thursday',
        'Fri' => 'Friday',
        'Sat' => 'Saturday',
        'Sun' => 'Sunday'
    ],

    'openHours' => [
        'closed' => 'Closed',
        '24hr' => 'All Day',
        '6AM' => '6 AM',
        '7AM' => '7 AM',
        '8AM' => '8 AM',
        '9AM' => '9 AM',
        '10AM' => '10 AM',
        '11AM' => '11 AM',
        '12PM' => '12 PM',
        '1PM' => '1 PM',
        '2PM' => '2 PM',
        '3PM' => '3 PM',
        '4PM' => '4 PM',
        '5PM' => '5 PM',
    ],

    'closedHours' => [
        'closed' => 'Closed',
        '24hr' => 'All Day',
        '11AM' => '11 AM',
        '12PM' => '12 PM',
        '1PM' => '1 PM',
        '2PM' => '2 PM',
        '3PM' => '3 PM',
        '4PM' => '4 PM',
        '5PM' => '5 PM',
        '6PM' => '6 PM',
        '7PM' => '7 PM',
        '8PM' => '8 PM',
        '9PM' => '9 PM',
        '10PM' => '10 PM',
        '11PM' => '11 PM',
        '12AM' => '12 AM',
        '1AM' => '1 AM',
        '2AM' => '2 AM',
    ],
];
